In [10]:
import pandas as pd
import matplotlib.pyplot as plt
import ast

In [11]:
df = pd.read_csv(r'D:\Data Analysis Project\New_MCD\Original - Copy\customers.csv')

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  10000 non-null  int64
 1   name         10000 non-null  str
 2   city         10000 non-null  str
dtypes: int64(1), str(2)
memory usage: 234.5 KB

In [22]:
df.sample(10)

      customer_id             name    city
8686         8687   Kasia Kowalski  Poznan
8150         8151      Jan Wozniak  Krakow
6421         6422     John Wozniak  Krakow
745           746        Jan Nowak  gdansk
6080         6081     Anna Wozniak  Krakow
3066         3067    Maria Wozniak  Warsaw
7931         7932   Anna Zielinski  Krakow
66             67  Marek Zielinski  Warsaw
2501         2502  Maria Zielinski  gdansk
8312         8313     Jan Kowalski  krakow

In [23]:
df['city'].unique()

<StringArray>
['Warsaw', 'warsaw', 'gdansk', 'Gdansk', 'krakow', 'Poznan', 'Krakow']
Length: 7, dtype: str

In [27]:
df['city'] = df['city'].str.capitalize()

In [28]:
df['city'].unique()

<StringArray>
['Warsaw', 'Gdansk', 'Krakow', 'Poznan']
Length: 4, dtype: str

In [29]:
df['name'].unique()

<StringArray>
[     'John Nowak',      'John Smith',    'Jan Kowalski',  'Anna Zielinski',
   'Maria Wozniak',      'Anna Nowak',   'Jan Zielinski',  'John Zielinski',
     'Jan Wozniak',     'Piotr Nowak',  'Marek Kowalski',     'Kasia Smith',
     'Kasia Nowak',     'Marek Smith', 'Kasia Zielinski', 'Piotr Zielinski',
   'John Kowalski',       'Jan Nowak',   'Piotr Wozniak',     'Piotr Smith',
   'Kasia Wozniak',     'Marek Nowak',   'Anna Kowalski',    'John Wozniak',
  'Piotr Kowalski',    'Anna Wozniak',     'Maria Smith',      'Anna Smith',
 'Marek Zielinski',  'Maria Kowalski',       'Jan Smith',  'Kasia Kowalski',
   'Marek Wozniak',     'Maria Nowak', 'Maria Zielinski']
Length: 35, dtype: str

In [30]:
df['name'] = df['name'].str.capitalize()

In [31]:
df['name'].unique()

<StringArray>
[     'John nowak',      'John smith',    'Jan kowalski',  'Anna zielinski',
   'Maria wozniak',      'Anna nowak',   'Jan zielinski',  'John zielinski',
     'Jan wozniak',     'Piotr nowak',  'Marek kowalski',     'Kasia smith',
     'Kasia nowak',     'Marek smith', 'Kasia zielinski', 'Piotr zielinski',
   'John kowalski',       'Jan nowak',   'Piotr wozniak',     'Piotr smith',
   'Kasia wozniak',     'Marek nowak',   'Anna kowalski',    'John wozniak',
  'Piotr kowalski',    'Anna wozniak',     'Maria smith',      'Anna smith',
 'Marek zielinski',  'Maria kowalski',       'Jan smith',  'Kasia kowalski',
   'Marek wozniak',     'Maria nowak', 'Maria zielinski']
Length: 35, dtype: str

In [32]:
df

      customer_id            name    city
0               1      John nowak  Warsaw
1               2      John smith  Warsaw
2               3    Jan kowalski  Gdansk
3               4  Anna zielinski  Warsaw
4               5   Maria wozniak  Warsaw
...           ...             ...     ...
9995         9996     Marek nowak  Warsaw
9996         9997  Piotr kowalski  Krakow
9997         9998  Marek kowalski  Krakow
9998         9999   Kasia wozniak  Warsaw
9999        10000     Kasia smith  Krakow

[10000 rows x 3 columns]

In [33]:
df.to_csv('customers_cleaned.csv', index=False)